# Generated by Django 4.1.7 on 2023-03-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_blog_blogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='second',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('imgs', models.ImageField(upload_to='picture')),
                ('catgryy', models.CharField(max_length=30)),
            ],
        ),
    ]
