# Generated by Django 4.1.7 on 2023-03-23 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_second'),
    ]

    operations = [
        migrations.RenameField(
            model_name='second',
            old_name='catgryy',
            new_name='date',
        ),
    ]
