# Generated by Django 4.1.7 on 2023-03-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_second_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
