# Generated by Django 4.1.7 on 2023-03-24 12:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_blogs_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
