# Generated by Django 4.1.7 on 2023-03-24 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_blogs_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='date',
        ),
    ]
